### ISSUE TITLE
General feedback

### ISSUE THREAD

**Issue by Some-of-the-things** [hellocoop/hello-nextjs-starter#8]
Hi,

I was looking to contribute to this after an initial conversation with Dick, who's a very interesting chap and obviously his work regarding OAuth 2.0 is a major thing. However, after having looked through the details and tried out the samples, I am concerned that this project seems to introduce an additional step in the user-journey while apparently not offering much more by way of functionality, apart from that all social login providers are in one place.

In addition, your material talks about an identity wallet and identity verification but it doesn't seem like there's much of either, as far as I can see. It may be that your nomenclature is at variance with what I currently understand or it could be that the functionality I was interested in is somehow not available in the part of the system where it seemed it was. Either way it didn't quite end up seeming as it first appeared. 

I am also unclear about exactly what your Co-Op business model is. I usually find that I'm able to parse legal docs like T&Cs etc with a little bit of effort but I ended my reading here with very little clarity on what the intended model is supposed to be and how it is supposed to work.

All this is a shame because I would be interested to work on digital identity but this doesn't seem to be quite what I thought.

**Comment by dickhardt** [comment]
Thanks for the feedback -- closing this as we have discussed directly.
